#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""
Migrate a v0.1.x sprint-status.yaml to the v0.2.0 BMAD-compatible format.

Usage:
  ./migrate-v0.2.py <path-to-sprint-status.yaml>

Reads the old format (list of story dicts with id/epic/title/status/dependsOn/...)
and writes the new format (development_status: flat key:status map, dependencies:
auto-extracted map). Backs up the original to .bak.<timestamp>.
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

import yaml


def migrate(old: dict) -> dict:
    stories = old.get("stories", []) or []
    if not stories:
        raise SystemExit("ERROR: no 'stories:' block found — already migrated, or wrong file.")

    # Group stories by epic, preserving epic-id order.
    by_epic: dict[str, list[dict]] = {}
    for s in stories:
        by_epic.setdefault(s["epic"], []).append(s)

    development_status: dict[str, str] = {}
    dependencies: dict[str, list[str]] = {}

    for epic_id in sorted(by_epic.keys()):
        # Aggregate epic status from its stories
        epic_stories = by_epic[epic_id]
        statuses = [s.get("status", "backlog") for s in epic_stories]
        if all(s == "done" for s in statuses):
            epic_status = "done"
        elif any(s in ("in-progress", "review", "ready-for-dev") for s in statuses):
            epic_status = "in-progress"
        elif any(s == "done" for s in statuses):
            epic_status = "in-progress"  # partial done = in-progress
        else:
            epic_status = "backlog"
        development_status[epic_id] = epic_status

        for s in epic_stories:
            development_status[s["id"]] = s.get("status", "backlog")
            deps = s.get("dependsOn") or []
            if deps:
                dependencies[s["id"]] = list(deps)

        development_status[f"{epic_id}-retrospective"] = "optional"

    sprint = old.get("sprint", {}) or {}
    new = {
        "generated": sprint.get("startedAt") or str(date.today()),
        "last_updated": str(date.today()),
        "project": sprint.get("name") or "Unnamed sprint",
        "story_location": ".agents/implementation/stories",
        "development_status": development_status,
        "dependencies": dependencies,
    }
    return new


def render(new: dict) -> str:
    """Render the new YAML with stable formatting and explicit comments."""
    lines: list[str] = []
    lines.append(f"generated: {new['generated']}")
    lines.append(f"last_updated: {new['last_updated']}")
    lines.append(f"project: {yaml.safe_dump(new['project']).strip()}")
    lines.append(f"story_location: {new['story_location']}")
    lines.append("")
    lines.append("development_status:")

    # Emit epic-by-epic with a blank line between epics
    ds = new["development_status"]
    current_epic: str | None = None
    for key, status in ds.items():
        if key.startswith("epic-") and not key.endswith("-retrospective"):
            if current_epic is not None:
                lines.append("")
            current_epic = key
        lines.append(f"  {key}: {status}")
    lines.append("")

    lines.append("# Auto-generated by flow-sprint from epic files. DO NOT edit manually.")
    lines.append("dependencies:")
    if not new["dependencies"]:
        lines.append("  {}")
    else:
        for sid, deps in new["dependencies"].items():
            arr = "[" + ", ".join(deps) + "]"
            lines.append(f"  {sid}: {arr}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    path = Path(sys.argv[1])
    if not path.exists():
        print(f"ERROR: {path} not found", file=sys.stderr)
        return 1

    old = yaml.safe_load(path.read_text())
    if "development_status" in (old or {}):
        print(f"NOOP: {path} is already in v0.2.0 format.")
        return 0

    new = migrate(old)
    rendered = render(new)

    # Validate that yaml can round-trip what we just produced
    yaml.safe_load(rendered)

    backup = path.with_suffix(path.suffix + f".bak.v0.1")
    counter = 0
    while backup.exists():
        counter += 1
        backup = path.with_suffix(path.suffix + f".bak.v0.1.{counter}")
    backup.write_text(path.read_text())

    path.write_text(rendered)
    print(f"OK: migrated {path}")
    print(f"     backup: {backup}")
    print(f"     {len(new['development_status'])} entries in development_status")
    print(f"     {len(new['dependencies'])} entries in dependencies")
    return 0


if __name__ == "__main__":
    sys.exit(main())
